export const projects = [
  {
    id: 1,
    title: "Bluebuck Designs",
    subtitle: "Portfolio",
    description: [
      "This is my first attempt at a portfolio website. A site where people can contact me for website design, development etc.",
      "It has separate sections showcasing my abilities and the different projects that I have worked on.",
    ],
    github: "",
    projLink: "",
    techStack: [
      "React JS",
      "Styled components",
      "Vite",
      "Vercel",
      "Framer motion",
    ],
    imageLink: "https://imgur.com/TEbANKp.png",
  },
  {
    id: 2,
    title: "Bike rental services",
    subtitle: "Mock site",
    description: [
      "A mock mobile site for users to come over and book bikes for rent",
      "Bikes are categorised under various headers and top bikes are shown as a infinitely looped carousel",
    ],
    github: "",
    projLink: "",
    techStack: ["React JS", "Tailwind Css", "Next JS", "Vercel"],
    imageLink: "https://imgur.com/Cqr7d7W.png",
  },
  {
    id: 3,
    title: "Desire AC services",
    subtitle: "Services",
    description: [
      "A mock website to showcase services provided by a Air conditioning service provider",
      "Built with both tailwind and styled-components provinding a complete control over the design system",
    ],
    github: "",
    projLink: "",
    techStack: [
      "React JS",
      "Tailwind Css",
      "Styled Components",
      "Next JS",
      "Vercel",
    ],
    imageLink: "https://imgur.com/Rv8pXJt.png",
  },
  {
    id: 4,
    title: "Covid 19 Vaccine Slots India",
    subtitle: "Health & COVID-19",
    description: [
      "A site built to have a quick glance at the Covid 19 vaccine slots making use of the Indian government's public COWIN apis. I built this initially only for my family and myself when searching via the Aarogyasetu app was a bit time consuming",
      "But then I ended up spending a bit more time to make any location/ hospital conducting vaccine drives searchable.",
    ],
    github: "",
    projLink: "",
    techStack: ["React JS", "Tailwind Css", "Next JS", "Vercel"],
    imageLink: "https://imgur.com/kwizgiy.png",
  },
];
